// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAJr-hvU8BxElzMKKsuoYwBX-sXm1dNF0',
    appId: '1:183000475013:web:548aa93880aa1b5a3990ec',
    messagingSenderId: '183000475013',
    projectId: 'bookease-78908',
    authDomain: 'bookease-78908.firebaseapp.com',
    storageBucket: 'bookease-78908.firebasestorage.app',
    measurementId: 'G-CHRELX46YX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbKV-ZnJh9AXIzs_xyKiL9yhuCI3ZDtJ4',
    appId: '1:183000475013:android:f1b4d675869aa61e3990ec',
    messagingSenderId: '183000475013',
    projectId: 'bookease-78908',
    storageBucket: 'bookease-78908.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbF11gs3cv85SETYW9paOId_7MZeFsP40',
    appId: '1:183000475013:ios:96a3b53ae51dbdd93990ec',
    messagingSenderId: '183000475013',
    projectId: 'bookease-78908',
    storageBucket: 'bookease-78908.firebasestorage.app',
    iosClientId: '183000475013-5erh0leotil083r0jsrf3f3dq1319rdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbF11gs3cv85SETYW9paOId_7MZeFsP40',
    appId: '1:183000475013:ios:96a3b53ae51dbdd93990ec',
    messagingSenderId: '183000475013',
    projectId: 'bookease-78908',
    storageBucket: 'bookease-78908.firebasestorage.app',
    iosClientId: '183000475013-5erh0leotil083r0jsrf3f3dq1319rdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookEase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAJr-hvU8BxElzMKKsuoYwBX-sXm1dNF0',
    appId: '1:183000475013:web:99101ff4d15dd3893990ec',
    messagingSenderId: '183000475013',
    projectId: 'bookease-78908',
    authDomain: 'bookease-78908.firebaseapp.com',
    storageBucket: 'bookease-78908.firebasestorage.app',
    measurementId: 'G-QWJ8ST20L8',
  );
}
